### PR TITLE
Pythonic code style changes

### PR DESCRIPTION
**Pull request by doctortoffu**
Hello there,

I made minor changes in coding style.
On line 28 I grouped in one line the creation of the dictionary for self.properties.
And on line 50 I renamed the function to follow traditional naming conventions in Python.

Cheers.

### CODE REVIEW

**Comment by grotewold** [comment]
Please fix failing unit tests.

Thanks!

**Comment by frewsxcv** [comment]
If you're busy, I can fix them for you, just let me know

**Comment by doctortoffu** [comment]
Hi Corey and Blake,

Sorry, I didn't notice the name of the function was being referred to from outside of the geojson folder!
I don't know how to fix that. I'm still new to git and GitHub.
Maybe you'd prefer to reject the changes? I'm okay with that, no hard feelings about it :-)

Cheers,
Rodrigo

**Comment by frewsxcv** [comment]
No worries, I'll take care of it!

**Comment by frewsxcv** [comment]
Merged in #72. Thanks!

**Pull request closed without merging**
