### PR TITLE
Add __getitem__ methods to sequence-like objects

### PR DESCRIPTION
**Pull request by JesseWeinstein**
Makes accessing them easier. I wasn't sure if it was a good idea to make them writable or not.

### CODE REVIEW

**Comment by frewsxcv** [comment]
Thanks for opening the PR! I hate to close PR contributions, but I'm going to refer to my answer I gave in https://github.com/frewsxcv/python-geojson/issues/80. It seems simple enough just to access the `coordinates` property and then do the indexing. Also, if you have a `Polygon(bbox = [...], coordinates=[...])`, and you attempt to index, it's not _super_ obvious if it would index `coordinates` or `bbox`. Sorry for closing, but thanks for the idea! 🙇

**Comment by JesseWeinstein** [comment]
Totally fine with you closing it, thank you for the prompt response. 

What other properties can a `Point` have aside from `coordinates`? It looked from my reading of the spec that it (along with the other geometry objects) were required to only have `type` and `coordinates` (and `bbox`, but that does not appear to be supported by this library, unless I'm missing something.)

**Comment by JesseWeinstein** [comment]
@frewsxcv -- one last question. The previous discussion addressed making the `coordinates` property implicitly indexable, but this PR also does the same for the `features` and `geometries` properties. I do feel that the case for making those properties implicitly indexable is stronger, as their objects ( `FeatureCollection` and `GeometryCollection`) explicitly describe themselves as "Collections", and have no other functionality aside from containing those arrays.

Please reconsider accepting this more limited PR.

**Comment by JesseWeinstein** [comment]
Whoops, it looks like I need to make a new PR to show this. I'll wait to hear if you'd be interested -- but you can review the code here: https://github.com/frewsxcv/python-geojson/compare/master...JesseWeinstein:add_getitem

**Comment by frewsxcv** [comment]
after giving it some more thought, i think this is change is okay. if it's possible, could you add a couple tests for this? if not, i can add some when i get some free time

**Comment by frewsxcv** [comment]
also fyi, added a merge commit to see how test coverage changes. feel free to get rid of the merge commit if you want

**Comment by JesseWeinstein** [comment]
Tests added, rebased off master. Merge away!

**Comment by frewsxcv** [comment]
thanks! bors r+

**Pull request merged**
